---
io-services:
  reader:
    class: org.jlab.epsci.stream.engine.evio.AggFileReaderEngine
    name: VTPSource
  writer:
    class: org.jlab.epsci.stream.engine.VTPWriterEngine
    name: VTPWriter
services:
   - class: org.jlab.epsci.stream.engine.evio.EvioFadcDecoderEngine
     name: VTPProcessor
configuration:
  services:
    VTPProcessor:
      sliding_widow_size: 16
      sliding_step: 1
#      beam_center: 1_3_12
mime-types:
  - binary/data-evio
