---
io-services:
  reader:
    class: org.jlab.epsci.stream.engine.evio.AggFileReaderEngine
    name: AggSource
  writer:
    class: org.jlab.epsci.stream.engine.evio.AggWriterEngine
    name: AggWriter
services:
   - class: org.jlab.epsci.stream.engine.evio.EvioFadcDecoderEngine
     name: AggProcessor
configuration:
  services:
    VTPProcessor:
      sliding_widow_size: 16
      sliding_step: 1
#      beam_center: "1_3_12"
mime-types:
  - binary/data-evio
  - binary/data-jobj
